using System;
using System.IO;
using System.Text;
using Microsoft.SqlServer.Dac;
using Microsoft.SqlServer.Dac.Model;

if (args.Length < 2)
{
    Console.Error.WriteLine("Usage: dacpac-extract <dacpac_path> <output_dir>");
    Console.Error.WriteLine("  Extracts DDL from a DacPac into tables.sql, views.sql,");
    Console.Error.WriteLine("  procedures.sql, and functions.sql in <output_dir>.");
    return 1;
}

var dacpacPath = args[0];
var outDir = args[1];

if (!File.Exists(dacpacPath))
{
    Console.Error.WriteLine($"Error: DacPac file not found: {dacpacPath}");
    return 1;
}

try
{
    Console.Error.WriteLine($"Loading DacPac: {Path.GetFileName(dacpacPath)}");
    using var model = new TSqlModel(dacpacPath, DacSchemaModelStorageType.Memory);
    Directory.CreateDirectory(outDir);

    int Write(string filename, string header, params ModelTypeClass[] typeClasses)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"-- {header}");
        sb.AppendLine($"-- Generated by dacpac-extract from {Path.GetFileName(dacpacPath)}");
        sb.AppendLine();
        int count = 0;
        foreach (var tc in typeClasses)
        {
            foreach (var obj in model.GetObjects(DacQueryScopes.UserDefined, tc))
            {
                if (obj.TryGetScript(out var script) && !string.IsNullOrWhiteSpace(script))
                {
                    sb.AppendLine(script);
                    sb.AppendLine("GO");
                    sb.AppendLine();
                    count++;
                }
            }
        }
        File.WriteAllText(Path.Combine(outDir, filename), sb.ToString(), Encoding.UTF8);
        return count;
    }

    int tables    = Write("tables.sql",     "Tables",             Table.TypeClass);
    int views     = Write("views.sql",      "Views",              View.TypeClass);
    int procs     = Write("procedures.sql", "Stored Procedures",  Procedure.TypeClass);
    int functions = Write("functions.sql",  "Functions",          ScalarFunction.TypeClass, TableValuedFunction.TypeClass);

    Console.Error.WriteLine($"Extracted: {tables} tables, {views} views, {procs} procedures, {functions} functions");
    return 0;
}
catch (Exception ex)
{
    Console.Error.WriteLine($"Error: {ex.Message}");
    return 1;
}
