WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE TABLE "__SCHEMA__"."BRONZE_CURRENCY" (
    "CURRENCYCODE" VARCHAR2(3) NOT NULL,
    "CURRENCYNAME" VARCHAR2(50) NOT NULL,
    "MODIFIEDDATE" DATE NOT NULL,
    CONSTRAINT "__SCHEMA___BRONZE_CURRENCY_PK" PRIMARY KEY ("CURRENCYCODE")
);
/

CREATE TABLE "__SCHEMA__"."BRONZE_PROMOTION" (
    "PROMOTIONID" NUMBER NOT NULL,
    "DESCRIPTION" VARCHAR2(255) NOT NULL,
    "DISCOUNTPCT" NUMBER(5,2),
    "PROMOTIONTYPE" VARCHAR2(50),
    "PROMOTIONCATEGORY" VARCHAR2(50),
    "STARTDATE" DATE NOT NULL,
    "ENDDATE" DATE,
    "MINQTY" NUMBER,
    "MAXQTY" NUMBER,
    "MODIFIEDDATE" DATE NOT NULL,
    CONSTRAINT "__SCHEMA___BRONZE_PROMOTION_PK" PRIMARY KEY ("PROMOTIONID")
);
/

CREATE TABLE "__SCHEMA__"."SILVER_CONFIG" (
    "CONFIGID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    "CONFIGKEY" VARCHAR2(100) NOT NULL,
    "CONFIGVALUE" VARCHAR2(255),
    CONSTRAINT "__SCHEMA___SILVER_CONFIG_PK" PRIMARY KEY ("CONFIGID"),
    CONSTRAINT "__SCHEMA___SILVER_CONFIG_UK" UNIQUE ("CONFIGKEY")
);
/

CREATE TABLE "__SCHEMA__"."SILVER_DIMCURRENCY" (
    "CURRENCYKEY" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    "CURRENCYALTERNATEKEY" VARCHAR2(3) NOT NULL,
    "CURRENCYNAME" VARCHAR2(50) NOT NULL,
    CONSTRAINT "__SCHEMA___SILVER_DIMCURRENCY_PK" PRIMARY KEY ("CURRENCYKEY")
);
/

CREATE TABLE "__SCHEMA__"."SILVER_DIMPROMOTION" (
    "PROMOTIONKEY" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    "PROMOTIONALTERNATEKEY" NUMBER,
    "CONFIGID" NUMBER DEFAULT 1 NOT NULL,
    "ENGLISHPROMOTIONNAME" VARCHAR2(255),
    "DISCOUNTPCT" NUMBER(5,2),
    "ENGLISHPROMOTIONTYPE" VARCHAR2(50),
    "ENGLISHPROMOTIONCATEGORY" VARCHAR2(50),
    "STARTDATE" DATE NOT NULL,
    "ENDDATE" DATE,
    "MINQTY" NUMBER,
    "MAXQTY" NUMBER,
    CONSTRAINT "__SCHEMA___SILVER_DIMPROMOTION_PK" PRIMARY KEY ("PROMOTIONKEY"),
    CONSTRAINT "__SCHEMA___SILVER_DIMPROMOTION_CONFIG_FK"
        FOREIGN KEY ("CONFIGID")
        REFERENCES "__SCHEMA__"."SILVER_CONFIG" ("CONFIGID")
);
/

MERGE INTO "__SCHEMA__"."BRONZE_CURRENCY" tgt
USING (
    SELECT 'USD' AS currency_code, 'US Dollar' AS currency_name FROM dual
    UNION ALL
    SELECT 'EUR' AS currency_code, 'Euro' AS currency_name FROM dual
    UNION ALL
    SELECT 'GBP' AS currency_code, 'Pound Sterling' AS currency_name FROM dual
) src
ON (tgt."CURRENCYCODE" = src.currency_code)
WHEN MATCHED THEN
    UPDATE SET
        tgt."CURRENCYNAME" = src.currency_name,
        tgt."MODIFIEDDATE" = SYSDATE
WHEN NOT MATCHED THEN
    INSERT ("CURRENCYCODE", "CURRENCYNAME", "MODIFIEDDATE")
    VALUES (src.currency_code, src.currency_name, SYSDATE);
/

MERGE INTO "__SCHEMA__"."BRONZE_PROMOTION" tgt
USING (
    SELECT
        1 AS promotion_id,
        'Spring Sale' AS description,
        10 AS discount_pct,
        'Seasonal' AS promotion_type,
        'Retail' AS promotion_category,
        DATE '2026-03-01' AS start_date,
        DATE '2026-05-31' AS end_date,
        1 AS min_qty,
        50 AS max_qty
    FROM dual
    UNION ALL
    SELECT
        2 AS promotion_id,
        'VIP Discount' AS description,
        15 AS discount_pct,
        'Targeted' AS promotion_type,
        'Loyalty' AS promotion_category,
        DATE '2026-01-01' AS start_date,
        DATE '2026-12-31' AS end_date,
        1 AS min_qty,
        10 AS max_qty
    FROM dual
) src
ON (tgt."PROMOTIONID" = src.promotion_id)
WHEN MATCHED THEN
    UPDATE SET
        tgt."DESCRIPTION" = src.description,
        tgt."DISCOUNTPCT" = src.discount_pct,
        tgt."PROMOTIONTYPE" = src.promotion_type,
        tgt."PROMOTIONCATEGORY" = src.promotion_category,
        tgt."STARTDATE" = src.start_date,
        tgt."ENDDATE" = src.end_date,
        tgt."MINQTY" = src.min_qty,
        tgt."MAXQTY" = src.max_qty,
        tgt."MODIFIEDDATE" = SYSDATE
WHEN NOT MATCHED THEN
    INSERT (
        "PROMOTIONID",
        "DESCRIPTION",
        "DISCOUNTPCT",
        "PROMOTIONTYPE",
        "PROMOTIONCATEGORY",
        "STARTDATE",
        "ENDDATE",
        "MINQTY",
        "MAXQTY",
        "MODIFIEDDATE"
    )
    VALUES (
        src.promotion_id,
        src.description,
        src.discount_pct,
        src.promotion_type,
        src.promotion_category,
        src.start_date,
        src.end_date,
        src.min_qty,
        src.max_qty,
        SYSDATE
    );
/

MERGE INTO "__SCHEMA__"."SILVER_CONFIG" tgt
USING (
    SELECT 1 AS config_id, 'full_reload' AS config_key, '1' AS config_value FROM dual
    UNION ALL
    SELECT 2 AS config_id, 'default_category' AS config_key, 'General' AS config_value FROM dual
    UNION ALL
    SELECT 3 AS config_id, 'cleanup_threshold' AS config_key, '1000' AS config_value FROM dual
) src
ON (tgt."CONFIGKEY" = src.config_key)
WHEN MATCHED THEN
    UPDATE SET
        tgt."CONFIGID" = src.config_id,
        tgt."CONFIGVALUE" = src.config_value
WHEN NOT MATCHED THEN
    INSERT ("CONFIGID", "CONFIGKEY", "CONFIGVALUE")
    VALUES (src.config_id, src.config_key, src.config_value);
/

CREATE OR REPLACE VIEW "__SCHEMA__"."SILVER_VW_DIMPROMOTION" AS
SELECT
    "PROMOTIONKEY",
    "PROMOTIONALTERNATEKEY",
    "ENGLISHPROMOTIONNAME",
    "DISCOUNTPCT",
    "ENGLISHPROMOTIONTYPE",
    "ENGLISHPROMOTIONCATEGORY",
    "STARTDATE",
    "ENDDATE",
    "MINQTY",
    "MAXQTY"
FROM "__SCHEMA__"."SILVER_DIMPROMOTION";
/

CREATE OR REPLACE PROCEDURE "__SCHEMA__"."SILVER_USP_LOAD_DIMCURRENCY" AS
    v_sql CLOB;
BEGIN
    DELETE FROM "__SCHEMA__"."SILVER_DIMCURRENCY";

    v_sql := q'[
        INSERT INTO "__SCHEMA__"."SILVER_DIMCURRENCY" ("CURRENCYALTERNATEKEY", "CURRENCYNAME")
        SELECT "CURRENCYCODE", "CURRENCYNAME"
        FROM "__SCHEMA__"."BRONZE_CURRENCY"
    ]';

    EXECUTE IMMEDIATE v_sql;
END "SILVER_USP_LOAD_DIMCURRENCY";
/

CREATE OR REPLACE PROCEDURE "__SCHEMA__"."SILVER_USP_LOAD_DIMPROMOTION" AS
BEGIN
    DELETE FROM "__SCHEMA__"."SILVER_DIMPROMOTION";

    INSERT INTO "__SCHEMA__"."SILVER_VW_DIMPROMOTION" (
        "PROMOTIONALTERNATEKEY",
        "ENGLISHPROMOTIONNAME",
        "DISCOUNTPCT",
        "ENGLISHPROMOTIONTYPE",
        "ENGLISHPROMOTIONCATEGORY",
        "STARTDATE",
        "ENDDATE",
        "MINQTY",
        "MAXQTY"
    )
    SELECT
        "PROMOTIONID",
        "DESCRIPTION",
        "DISCOUNTPCT",
        "PROMOTIONTYPE",
        "PROMOTIONCATEGORY",
        "STARTDATE",
        "ENDDATE",
        "MINQTY",
        "MAXQTY"
    FROM "__SCHEMA__"."BRONZE_PROMOTION";
END "SILVER_USP_LOAD_DIMPROMOTION";
/

CREATE OR REPLACE PROCEDURE "__SCHEMA__"."SILVER_USP_UNIONALL" AS
BEGIN
    DELETE FROM "__SCHEMA__"."SILVER_CONFIG"
    WHERE "CONFIGKEY" LIKE 'currency_%';

    INSERT INTO "__SCHEMA__"."SILVER_CONFIG" ("CONFIGKEY", "CONFIGVALUE")
    SELECT 'currency_' || LOWER("CURRENCYCODE"), "CURRENCYNAME"
    FROM "__SCHEMA__"."BRONZE_CURRENCY"
    WHERE "CURRENCYCODE" <= 'M'
    UNION ALL
    SELECT 'currency_' || LOWER("CURRENCYCODE"), "CURRENCYNAME"
    FROM "__SCHEMA__"."BRONZE_CURRENCY"
    WHERE "CURRENCYCODE" > 'M';
END "SILVER_USP_UNIONALL";
/

COMMIT;
/
